---
chdir: /home/muaddib/www/ankidict.weitnahbei.de/installations/ankidict_arde-dear
environment: development
address: 127.0.0.1
port: 47123
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
daemonize: true
